table Roles
	lineageTag: 1fcf4f27-21d5-428e-853d-ba9a0680f531

	column Roles
		dataType: string
		lineageTag: bf92e4c6-1999-4702-a471-6eba4c36e0fe
		summarizeBy: none
		sourceColumn: Roles

		annotation SummarizationSetBy = Automatic

	column 'Roles Description'
		dataType: string
		lineageTag: 5ddc0598-c16a-4497-9981-432f31373c0d
		summarizeBy: none
		sourceColumn: Roles Description

		annotation SummarizationSetBy = Automatic

	column 'Roles Id'
		dataType: int64
		formatString: 0
		lineageTag: 27ff2209-c4fb-49d6-8c42-9e938408641c
		summarizeBy: none
		sourceColumn: Roles Id

		annotation SummarizationSetBy = Automatic

	column 'Role images'
		dataType: string
		lineageTag: 788753e1-669e-4733-9f68-276a6e60b83d
		summarizeBy: none
		sourceColumn: Role images

		annotation SummarizationSetBy = Automatic

	partition Roles = m
		mode: import
		source = ```
				let
				  Source = Csv.Document(
				    File.Contents("D:\Valorant Dataset\Data\Roles.csv"), 
				    [Delimiter = ",", Columns = 3, Encoding = 1252, QuoteStyle = QuoteStyle.None]
				  ), 
				  Custom1 = Table.PromoteHeaders(Source, [PromoteAllScalars = true]), 
				  #"Changed Type" = Table.TransformColumnTypes(
				    Custom1, 
				    {{"Roles", type text}, {"Roles Description", type text}, {"Roles Image Links", type text}}
				  ), 
				  #"Added Custom" = Table.AddColumn(
				    #"Changed Type", 
				    "Roles Id", 
				    each 
				      let
				        condition = {
				          [Roles] = "Controllers", 
				          [Roles] = "Duelists", 
				          [Roles] = "Initiators", 
				          [Roles] = "Sentinels"
				        }, 
				        result = {1, 2, 3, 4}
				      in
				        result{List.PositionOf(condition, true)}, Int64.Type
				  ),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Role images", each Text.BeforeDelimiter([Roles Image Links], "/revision"), type text),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom1",{"Roles Image Links"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"Roles Id", "Roles", "Roles Description", "Role images"})
				in
				    #"Reordered Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

